'use strict';

const fs = require('fs');
const path = require('path');
const { buildMvDraw3dHtml } = require('../../scripts/mv-draw/mvdraw-3d-html');

const DEFAULT_OUT_DIR = path.join(__dirname, '..', '..', 'public', 'samples');

function slugFromProject(doc, hint = '') {
  const fromHint = String(hint || '').trim().replace(/[^\w.-]+/g, '-').toLowerCase();
  if (fromHint) return fromHint;
  const name = String(doc?.name || '').trim().replace(/[^\w.-]+/g, '-').toLowerCase();
  return name && name !== 'untitled' ? name : 'site';
}

function buildSiteConfigJs(site) {
  return `// Generated by mv-draw artifact pipeline — do not edit.
export const SITE = ${JSON.stringify(site, null, 2)};
`;
}

function facility3dUrlForSlug(slug) {
  return `/samples/${slug}-mvdraw-3d.html`;
}

/**
 * Write site config + HTML viewer for an MV Draw scene.
 * @param {object} site — buildSceneFromMvDraw() output
 * @param {string} slug
 * @param {{ outDir?: string }} opts
 */
function writeMvDraw3dArtifacts(site, slug, opts = {}) {
  const outDir = opts.outDir || DEFAULT_OUT_DIR;
  const safeSlug = String(slug || 'site').replace(/[^\w.-]+/g, '-').toLowerCase() || 'site';
  const configName = `${safeSlug}-site-config.js`;
  const htmlName = `${safeSlug}-mvdraw-3d.html`;
  const configRel = `./${configName}`;

  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, configName), buildSiteConfigJs(site), 'utf8');
  fs.writeFileSync(
    path.join(outDir, htmlName),
    buildMvDraw3dHtml(site, {
      title: `${site.name} — MV Draw 3D`,
      subtitle: `${site.placements.length} symbols · ${site.pipes.length} pipes · ${site.zones?.length || 0} zones`,
      configFile: configRel,
    }),
    'utf8',
  );

  return {
    slug: safeSlug,
    configName,
    htmlName,
    configPath: path.join(outDir, configName),
    htmlPath: path.join(outDir, htmlName),
    url: facility3dUrlForSlug(safeSlug),
  };
}

module.exports = {
  slugFromProject,
  buildSiteConfigJs,
  facility3dUrlForSlug,
  writeMvDraw3dArtifacts,
};
