'use strict';

/** @typedef {import('./project-config-types')} ProjectConfig */

const MLE_2000 = {
  id: 'mle-2000gpd',
  pdfFile: 'MLE-2000GPD-CRS-Project-Design.pdf',
  footerTitle: 'MLE 2,000 GPD WWTP',
  coverTitle: 'MLE Package WWTP',
  coverSubtitle: '2,000 GPD · Fixed PVA IFAS · CRS Nanobubble Aeration',
  siteName: 'Decentralized package site',
  county: 'Generic',
  state: 'US',
  pfdSubtitle:
    '2,000 GPD MLE-IFAS · CRS · s::can optical loop · BOD/NH3/NO3/TSS/pH/ORP · AI · Effluent <=10 mg/L NO3-N',
  layout: 'single', // single | dual-125k
  flowAvgGpd: 2000,
  flowPeakGpd: 4000,
  flowAvgGph: 83,
  flowAvgGpm: 1.4,
  reactorGal: 4000,
  anoxicGal: 1400,
  aerobicGal: 2600,
  settlerGal: 400,
  trains: 1,
  trainLabel: '4,000 gal Package Reactor',
  hrtDays: 2.0,
  irRatio: 3.5,
  irGpd: 7000,
  irGpm: 5,
  rasPct: 75,
  rasGpd: 1500,
  rasGpm: 1,
  wasGpd: '5-10',
  mooreviewProject: 'mle-wastewater',
  influentBod: 200,
  influentTss: 180,
  influentTkn: 40,
  influentNh3: 30,
  influentTn: 45,
  designMinTempC: 10,
  anoxTssTarget: '1,500-3,500 mg/L',
  midCapex: 200000,
  totalBudget: 275000,
  annualOpex: '6,000-9,000',
  footprintSqFt: '120-150',
  crsSidestreamGpm: '10-15',
  crsLineSize: '1"',
  backupBlowerHp: 0.15,
  anoxicMixerHp: 0.25,
  sidestreamPumpHp: 0.33,
  o2DemandLbD: '0.8-1.2',
  pvaFt3: 170,
  mlss: '2,000-3,000',
  scanPackageCapex: 55000,
  scanDwellMin: 8,
  notes: [
    'Confirm whether permit limit is NO3-N (as nitrogen) or NO3 as ion (stricter).',
    'If limit is NO3 ion at 10 mg/L (~2.3 mg/L as N), add post-denitrification filter.',
    's::can recirculating optical loop on all MLE phases — calibrate BOD/COD vs lab monthly.',
  ],
};

const PASCO_RV_120K = {
  id: 'pasco-rv-120kgpd',
  pdfFile: 'Pasco-RV-120KGPD-MLE-Project-Design.pdf',
  footerTitle: 'Pasco RV Resort — 120,000 GPD MLE WWTP',
  coverTitle: 'Pasco RV Resort — MLE WWTP',
  coverSubtitle: '120,000 GPD · 2×125K gal MLE-IFAS · CRS · AI-ready',
  siteName: 'Pasco RV Resort',
  county: 'Pasco County',
  state: 'Florida',
  pfdSubtitle:
    'Pasco RV · 120K GPD · 2×125K MLE-IFAS · CRS · s::can 6-port loop · BOD/pH/ORP · AI · <=10 mg/L NO3-N',
  layout: 'dual-125k',
  flowAvgGpd: 120000,
  flowPeakGpd: 240000,
  flowAvgGph: 5000,
  flowAvgGpm: 83,
  reactorGal: 250000,
  anoxicGal: 87500,
  aerobicGal: 162500,
  settlerGal: 12000,
  perTrainGal: 125000,
  perTrainAnoxicGal: 43750,
  perTrainAerobicGal: 81250,
  perTrainFlowGpd: 60000,
  trains: 2,
  trainLabel: '2×125,000 gal Integrated MLE Trains (parallel)',
  hrtDays: 2.08,
  irRatio: 3.5,
  irGpd: 420000,
  irGpm: 291,
  irGpmPerTrain: 146,
  rasPct: 75,
  rasGpd: 90000,
  rasGpm: 62,
  wasGpd: '300-600',
  influentBod: 250,
  influentTss: 220,
  influentTkn: 45,
  influentNh3: 35,
  influentTn: 50,
  designMinTempC: 15,
  anoxTssTarget: '2,500-4,500 mg/L',
  midCapex: 1435000,
  totalBudget: 1750000,
  annualOpex: '45,000-65,000',
  footprintSqFt: '2,500-3,500',
  crsSidestreamGpm: '80-150 per train',
  crsLineSize: '2"',
  backupBlowerHp: 7.5,
  anoxicMixerHp: 2,
  sidestreamPumpHp: 3,
  o2DemandLbD: '350-450',
  pvaFt3: 10200,
  mlss: '2,500-4,000',
  eqBasinGal: 50000,
  scanPackageCapex: 85000,
  scanDwellMin: 10,
  clarifierNote: '2× secondary clarifiers ~45 ft dia OR single 65 ft central clarifier',
  mooreviewProject: 'pasco-rv-mle',
  notes: [
    'Pasco County / FDEP: confirm NPDES or individual wastewater permit for RV resort classification.',
    'Design for seasonal peaking (snowbird occupancy); EQ basin recommended for diurnal/weekly surges.',
    'RV influent: elevated grease and surfactants — bar screen + grease interceptor upstream; monitor ANOX_TSS.',
    'Florida min temp 15°C supports higher nitrifier rates; size SRT for 12-day winter equivalent.',
    'Pasco County reuse/disposal: confirm effluent disposal (surface water, reuse, or deep well).',
  ],
};

const MLE_POC_50GPD = {
  id: 'mle-poc-50gpd',
  pdfFile: 'MLE-POC-50GPD-Project-Design.pdf',
  footerTitle: 'MLE POC — 50 GPD WWTP',
  coverTitle: 'MLE Proof-of-Concept WWTP',
  coverSubtitle: '50 GPD · Fixed PVA IFAS · CRS Nanobubbles · s::can · AI',
  siteName: 'POC demonstration skid / bench-scale pilot',
  county: 'Generic',
  state: 'US',
  pfdSubtitle:
    '50 GPD POC · separate process tanks · 270 gal IBC clarifier · 200 gal final · s::can · AI',
  layout: 'poc-tote',
  isPoc: true,
  flowAvgGpd: 50,
  flowPeakGpd: 100,
  flowAvgGph: 2.1,
  flowAvgGpm: 0.035,
  reactorGal: 100,
  anoxicGal: 35,
  aerobicGal: 65,
  settlerGal: 270,
  clarifierGal: 270,
  clarifierLabel: '270 gal chemical tote (IBC) — secondary clarifier',
  finalTankGal: 200,
  finalTankLabel: '200 gal low-profile final treatment / sampling tank',
  trains: 1,
  trainLabel: 'POC skid — separate process tanks · 270 gal IBC clarifier · 200 gal final',
  hrtDays: 2.0,
  irRatio: 3.5,
  irGpd: 175,
  irGpm: 0.12,
  rasPct: 75,
  rasGpd: 38,
  rasGpm: 0.03,
  wasGpd: '0.2-0.5',
  influentBod: 200,
  influentTss: 180,
  influentTkn: 40,
  influentNh3: 30,
  influentTn: 45,
  designMinTempC: 10,
  anoxTssTarget: '1,500-3,500 mg/L',
  midCapex: 165000,
  totalBudget: 240000,
  annualOpex: '4,000-6,000',
  footprintSqFt: '120-160',
  crsSidestreamGpm: '1-2',
  crsLineSize: '3/4"',
  backupBlowerHp: 0.05,
  anoxicMixerHp: 0.1,
  sidestreamPumpHp: 0.1,
  o2DemandLbD: '0.05-0.15',
  pvaFt3: 8,
  mlss: '2,000-3,500',
  scanPackageCapex: 55000,
  scanDwellMin: 8,
  mooreviewProject: 'mle-poc-50gpd',
  /** T-200 IBC bottom insert — three hydraulic zones (see Detail A on drawings). */
  toteBottomInsert: {
    coneInsert: 'HDPE funnel insert, 45° slope, 14" drop to center apex (flat-bottom IBC)',
    standpipe: '2" PVC center standpipe, rim adjustable 28–36" above tote floor (sets sludge interface)',
    ibcFootprint: '48" L × 40" W (typical 275 gal IBC pallet; verify before fab)',
    insertRim: '36" × 28" OD at tote floor; 3/8" HDPE (10 mm) machined + welded seams',
    funnelApexDrop: '14" below insert rim plane',
    wasOffset: '5" vertical above apex; 180° from RAS on cone slope',
    standpipeRim: '28–36" above tote floor (commission to 2–4" above sludge interface)',
    zones: [
      {
        id: '1',
        name: 'RAS sump',
        port: 'L-RAS',
        size: '2" FNPT / camlock bulkhead',
        elevation: 'Cone apex — absolute low point',
        service: 'Thickened sludge → P-RAS → T-100 anoxic',
      },
      {
        id: '2',
        name: 'WAS draw',
        port: 'L-WAS',
        size: '1" FNPT bulkhead + ball valve',
        elevation: 'Cone slope, 5" vertical above apex (180° from RAS)',
        service: 'Sludge blanket waste → TV-WAS → holding tote',
      },
      {
        id: '3',
        name: 'Overflow (clarified)',
        port: 'L-210',
        size: '2" tee from standpipe; HV-210 isolation',
        elevation: 'Standpipe open top / rim — above sludge interface only',
        service: 'Supernatant → T-210 final tank (not sludge)',
      },
    ],
    bom: [
      { item: 'HDPE funnel insert', qty: '1', spec: '3/8" HDPE sheet; 45° cone; 14" apex drop; rim gasket groove', notes: 'Machine/weld; bond EPDM rim gasket' },
      { item: 'RAS bulkhead fitting', qty: '1', spec: '2" PP/SS tank adapter (Banjo TF200 or equiv.)', notes: 'Zone 1 — cone apex center; 2" FNPT out' },
      { item: 'RAS camlock adapter', qty: '1', spec: '2" male camlock × FNPT', notes: 'Quick-disconnect for P-RAS suction hose' },
      { item: 'WAS bulkhead fitting', qty: '1', spec: '1" PP tank adapter (Banjo TF100 or equiv.)', notes: 'Zone 2 — drill on cone slope per template' },
      { item: 'WAS isolation valve', qty: '1', spec: '1" PVC true-union ball valve (TV-WAS)', notes: 'Mount outside tote; timed waste draw' },
      { item: 'Standpipe (vertical)', qty: '1', spec: '2" PVC Sch 40 pipe, 30" long', notes: 'Trim to set rim height; solvent-weld to tee' },
      { item: 'Standpipe tee', qty: '1', spec: '2" PVC Sch 40 tee (Spears 402-020 or equiv.)', notes: 'Branch = L-210 overflow; mount 12–16" above floor' },
      { item: 'Overflow outlet', qty: '1', spec: '2" PVC Sch 40 × 18" nipple + 90° elbow', notes: 'Horizontal run through tote wall to L-210' },
      { item: 'Overflow isolation valve', qty: '1', spec: '2" PVC true-union ball valve (HV-210)', notes: 'Downstream of tee branch, outside tote' },
      { item: 'Standpipe union', qty: '1', spec: '2" PVC union', notes: 'Above tee — allows rim height adjustment without cutting' },
      { item: 'Standpipe support bracket', qty: '1', spec: '304 SS unistrut or angle + U-bolt', notes: 'Anchor to tote cage; do not load bulkheads' },
      { item: 'Insert hold-down', qty: '4', spec: '1/4" × 2" SS bolt + fender washer + EPDM', notes: 'Through rim flange into tote floor pad (seal only)' },
      { item: 'Rim gasket', qty: '1', spec: '3/16" EPDM strip or closed-cell neoprene', notes: 'Continuous perimeter under insert rim' },
      { item: 'PVC cement / primer', qty: '1 lot', spec: 'Weld-On P-68 + 795', notes: 'Standpipe assembly only; no solvent on HDPE' },
      { item: 'Wall penetration seal', qty: '2', spec: '2" and 1" conduit/tank seals (optional)', notes: 'Where L-210 and L-WAS exit tote sidewall' },
    ],
    assembly: [
      'Confirm IBC is dedicated clarifier (not chemical service). Drain, rinse, air-dry.',
      'Template Zone 1 apex, Zone 2 WAS (180° opposite), and standpipe center on tote floor from plan view.',
      'Install HDPE funnel insert with rim gasket; torque hold-down bolts evenly — watertight, not structural.',
      'Install 2" RAS bulkhead at apex; 1" WAS bulkhead on cone slope at +5" elevation.',
      'Solvent-weld standpipe: floor flange or pass-through at center → tee at 12–16" AFF → union → 30" riser (open top).',
      'Tee branch horizontal through sidewall penetration → HV-210 → L-210 to T-210.',
      'Pressure-test insert rim and bulkheads with water to 6" above standpipe rim before biological startup.',
      'After 7–10 days operation, adjust standpipe rim 2–4" above observed sludge interface.',
    ],
  },
  notes: [
    'POC objective: validate MLE + PVA IFAS + CRS nanobubbles + s::can optical loop + AI control at 50 GPD before full-scale deployment.',
    'Physical layout: individual 35 gal anoxic + 65 gal aerobic process tanks; 270 gal chemical tote (IBC) as secondary clarifier with 3-zone bottom insert (RAS sump / WAS draw / standpipe overflow); bottom drain to 200 gal low-profile final tank.',
    'Biological HRT ~2 days on 100 gal process volume @ 50 GPD; clarifier and final tanks provide surge capacity and permit-grade sample point.',
    'Permit: may operate under pilot/research authorization or temporary permit; confirm with local authority.',
    's::can recirculating loop and MooreVIEW historian capture 90+ days training data for AI model.',
    'If limit is NO3 ion at 10 mg/L (~2.3 mg/L as N), add post-denitrification filter.',
  ],
};

const CONFIGS = {
  'mle-2000gpd': MLE_2000,
  'pasco-rv-120kgpd': PASCO_RV_120K,
  'mle-poc-50gpd': MLE_POC_50GPD,
  'mle-poc-5gpm': MLE_POC_50GPD,
};

function getProjectConfig(id) {
  const cfg = CONFIGS[id];
  if (!cfg) {
    const keys = Object.keys(CONFIGS).join(', ');
    throw new Error(`Unknown project "${id}". Available: ${keys}`);
  }
  return cfg;
}

function fmtGpd(n) {
  return n.toLocaleString('en-US');
}

function fmtMoney(n) {
  if (n >= 1_000_000) return `~$${(n / 1_000_000).toFixed(2)}M`;
  return `~$${n.toLocaleString('en-US')}`;
}

module.exports = { CONFIGS, getProjectConfig, fmtGpd, fmtMoney };
